export const seedConcerts = [
  {
    title: 'Кино — Легендарные концерты',
    date: new Date('1990-05-24T19:00:00.000Z'),
    country: 'Россия',
    city: 'Москва',
    place: 'Лужники',
    link: 'https://example.com/concert/kino-moscow',
  },
  {
    title: 'Мумий Тролль — Концерт в Кремле',
    date: new Date('2025-06-15T20:00:00.000Z'),
    country: 'Россия',
    city: 'Москва',
    place: 'Кремлёвский дворец',
    link: 'https://example.com/concert/mumiy-kremlin',
  },
  {
    title: 'Би-2 — Большой сольный концерт',
    date: new Date('2025-07-01T19:30:00.000Z'),
    country: 'Россия',
    city: 'Санкт-Петербург',
    place: 'БЦЗ',
    link: 'https://example.com/concert/bi2-spb',
  },
  {
    title: 'Земфира — Тур 2025',
    date: new Date('2025-08-10T20:00:00.000Z'),
    country: 'Россия',
    city: 'Москва',
    place: 'Стадион Открытие Банк Арена',
    link: 'https://example.com/concert/zemfira-tour',
  },
  {
    title: 'Сплин — Acoustic Night',
    date: new Date('2025-09-05T19:00:00.000Z'),
    country: 'Россия',
    city: 'Москва',
    place: 'Крокус Сити Холл',
    link: 'https://example.com/concert/splean-acoustic',
  },
  {
    title: 'Ленинград — Юбилейный концерт',
    date: new Date('2025-10-20T20:00:00.000Z'),
    country: 'Россия',
    city: 'Санкт-Петербург',
    place: 'Ледовый дворец',
    link: 'https://example.com/concert/leningrad-anniversary',
  },
  {
    title: 'ДДТ — Рок легенды',
    date: new Date('2025-11-12T19:00:00.000Z'),
    country: 'Россия',
    city: 'Екатеринбург',
    place: 'Екатеринбург-Арена',
    link: 'https://example.com/concert/ddt-legends',
  },
  {
    title: 'Аквариум — 50 лет на сцене',
    date: new Date('2025-12-01T18:00:00.000Z'),
    country: 'Россия',
    city: 'Санкт-Петербург',
    place: 'БКЗ Октябрьский',
    link: 'https://example.com/concert/aquarium-50',
  },
  {
    title: 'Metallica — WorldWired Tour',
    date: new Date('2025-07-25T20:00:00.000Z'),
    country: 'Россия',
    city: 'Москва',
    place: 'Стадион Лужники',
    link: 'https://example.com/concert/metallica-moscow',
  },
  {
    title: 'Linkin Park — From Zero Tour',
    date: new Date('2025-08-18T19:30:00.000Z'),
    country: 'Россия',
    city: 'Москва',
    place: 'ВТБ Арена',
    link: 'https://example.com/concert/linkinpark-tour',
  },
  {
    title: 'Rammstein — Europe Stadium Tour',
    date: new Date('2025-06-28T19:00:00.000Z'),
    country: 'Германия',
    city: 'Берлин',
    place: 'Олимпийский стадион',
    link: 'https://example.com/concert/rammstein-berlin',
  },
  {
    title: 'Depeche Mode — Memento Mori Tour',
    date: new Date('2025-09-14T20:00:00.000Z'),
    country: 'Великобритания',
    city: 'Лондон',
    place: 'O2 Arena',
    link: 'https://example.com/concert/depeche-london',
  },
];
